services:
  - type: web
    name: backend
    plan: free
    runtime: node
    repo: https://github.com/ulut0002/monorepo
    rootDir: apps/backend
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
