/**
 * Machine-readable error codes used across API responses.
 */
export enum MessageCodes {
  VALIDATION_ERROR = "VALIDATION_ERROR",
  MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",
  MISSING_SECURITY_KEY = "MISSING_SECURITY_KEY",
  REQUIRED_FIELD = "REQUIRED_FIELD",
  INVALID_EMAIL = "INVALID_EMAIL",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  EXISTING_USER = "EXISTING_USER",
  AUTH_FAILED = "AUTH_FAILED",
  SERVER_ERROR = "SERVER_ERROR",
  NOT_FOUND = "NOT_FOUND",
}
